
spring.application.name=resident_management_system

#PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/rms_db
spring.datasource.username=rms_user
spring.datasource.password=rms_password

#JPA configuration
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
